matrix:
  include:
  - os: osx
    osx_image: xcode12
    language: cpp
    addons:
      homebrew:
        packages:
          - gtkmm3
          - zlib
          - cpr

branches:
  only:
    - cmake
